apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops
  labels:
    app: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      containers:
      - name: devsecops-container
        image: sarvjeet908/udemy:4
---
apiVersion: v1
kind: Service
metadata:
  name: devsecops-svc        # <-- moved here
  labels:
    app: devsecops
spec:
  selector:
    app: devsecops
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
